CREATE DATABASE IF NOT EXISTS Cine;
USE Cine;

CREATE TABLE Salas(
Codigo INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(100),
Pelicula INT,
KEY FK_Pelicula (Pelicula)
);

CREATE TABLE Peliculas(
Codigo INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(100),
CalificacionEdad INT);

CREATE TABLE Scripts(
Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
Version INT NOT NULL,
Nombre VARCHAR(22) NOT NULL,
Fecha DATE NOT NULL);

INSERT INTO Scripts
VALUES( 1, 001, "Linea base", '2019_11_13');
